---
- name: create users group
  group: name=users state=present
  sudo: yes
  tags:
    - setusers

- name: create listed users
  user: name={{ item.name }} group={{ item.group }} state=present
  sudo: yes
  with_items: users
  tags:
    - setusers

- name: add SSH keys
  authorized_key: user={{ item.0.name }} key='{{ item.1 }}'
  sudo: yes
  with_subelements:
    - users
    - keys
  tags:
    - setusers
    - setsshkeys