---
- name: ensure wheel can run sudo
  lineinfile: "dest={{ sudoers_location }} state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
  sudo: yes
  tags:
    - setsudoers
